version: '3.2'

services:
  flutter:
    build:
      context: flutter_form/
    ports:
      - "8080:8080"
    networks:
      - wb

  flask:
    build:
      context: flask_docker/
    ports:
      - "5000:5000"
    networks:
      - wb